name: Package Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create ZIP
        run: |
          zip -r 2-4-Decoder.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x "2-4-Decoder.zip"

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
          2-4-Decoder.zip \
          --generate-notes