name: Package Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create ZIP
        run: |
          mkdir 2-1-MUX
          cp -r . 2-1-MUX
          rm -rf 2-1-MUX/.git
          rm -rf 2-1-MUX/.github
          zip -r 2-1-MUX.zip 2-1-MUX

      - name: Upload ZIP to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" \
          2-1-MUX.zip \
          --clobber